### PR TITLE
Correct rounding

### PR DESCRIPTION
**Pull request by pthariensflame**

### CODE REVIEW

**Comment by davidcarlisle** [comment]
there really is no need to have anything like that number of digits (before or after the pull request) consider

```

\ifdim 0.1666666666666em = 0.16667em
yes
\else
no
\fi

\bye

```

which shows at typical 10pt size 5 decimal points is plenty. Any additional digits in the input make no difference.

**Comment by wilx** [comment]
I have merged this and subsequently, I have truncated the sizes down to just 5 digits after period.

**Comment by jfbu** [comment]
Whenever TeX inputs a dimension, it first does *not* look at the dimension unit, and it rounds the decimal number to the nearest integer multiple of 1/65536. Only *after* having done that does TeX look at the dimension unit and use it  as a conversion factor to sp units. Thus the granularity is 1/65536 em and using more digits can not go beyond that circa 0.00001526 em. Thus it does not bring much to go beyond 5 digits after decimal mark, because whatever you do you can not achieve finer than  0.00001526 em precision (as @davidcarlisle says 1em is usually about 10pt = 655360 sp, so this granularity is 10sp which is already tiny and close to the absolute minimal 1sp TeX can handle) There is a mathematical result used by Knuth that 17 digits after decimal mark are enough to be sure nothing will change if you add more digits. But already with 5 digits after mark, all you can hope by adding more digits is to modify result by at most by 10sp.

This being said try this with etex executable, and you can see that TeX conversion process may multiply relative error by more than 15 !

```
% \number\dimexpr1em\relax

\number\dimexpr0.53112em\relax % 348070sp

\number\dimexpr0.531121em\relax % 348080sp

% relative difference in input is 
% 1/531120

% relative difference in output is
% 10/348070 = 1/34807 which is

% more than 15 times bigger !!

\bye
```

Side note: for reasons I ignore, `1em` gives `655361sp` and not `655360sp` which would be exactly `10pt`.  I actually don't know how the `em` dimension is coded in the TeX font file, I imagine there is conversion effect here which explains `655361sp`.

**Comment by jfbu** [comment]
relative error can be multiplied by gigantic factor when you do need the 17 digits to ensure the exact rounding... but I have not investigated when we fix the first 5 digits and see how we can perturbate. In example above we can take 0.53112pt and 0.5311204pt and get 1sp difference, we have multiplied realtive error by more than 30 ! But, I don't want to abuse your issue tracker here, so I will stop...

**Comment by jfbu** [comment]
ok I will abuse your issue tracker with a last one (I don't come back don't worry after that): consider `0.98069em` versus `0.980690003em`. Internally the first one gets converted to `642700sp` and the second one to `642710sp`. We have converted a relative error of `3` parts in `1,000,000,000` into a relative error of about `1,5` parts in `100,000`, hence an unstability factor of circa `20000` ... anyway, all of this to explain why Knuth keeps 17 digits after decimal mark. A final remark is that the bigger the dimension unit, the less accurate are TeX conversions. This is why the French metric system `1cm` is much better than the anglo-saxon `1in` ... `;-)` but anyway it is better to use the smaller `pt` unit, also because it is handled faster internally as there is no conversion factor after first step of the dimension input. Or one goes for `sp` unit and expresses all in whole numbers. Then one gets exactly what one wants.

**Comment by wilx** [comment]
@jfbu I am reading your comments but I am not sure what to take from them. Feel free create a pull request with your proposed changes. If you do so, please attach some description of why more digits are necessary.

**Comment by davidcarlisle** [comment]
While the comments from @jfbu about tex rounding are I think true as a general statement I don't think it really matters in this context at all. You can't avoid the issue by using  pt or sp as you want the values to depend on the current font, and the exact size of 1em is entirely arbitrary, whatever value is in fontdimen 6, so to be honest 2 decimal places is enough,  However rather than have magic decimals in the code you could let (e)tex sort it out and do the divisions which leads to perhaps clearer code.
While this costs you a division per use it saves you parsing a string of 6's so I think it's not that inefficient.
```

% three-per-em space
\newunicodechar{ }{\hspace{\dimexpr 1em/3\relax}}

% four-per-em space
\newunicodechar{ }{\hspace{\dimexpr 1em/4\relax}}

% six-per-em space
\newunicodechar{ }{\hspace{\dimexpr 1em/6\relax}}

% figure space
\newunicodechar{ }{\hspace{\fontcharwd \font `\0}

% punctuation space
\newunicodechar{ }{\hspace{\fontcharwd \font `\,}}

% thin space
\newunicodechar{ }{\leavevmode\allowbreak\,}

% hair space
\newunicodechar{ }{\hspace{\dimexpr 1em/12\relax}}

```

**Comment by jfbu** [comment]
Hi @wilx @davidcarlisle I know my comments were sort of off-topic, but once I embarked upon this, it got too complicated to stop, I was not trying to contribute but just got triggered by the ``\ifdim0.1666666666666em = 0.16667em`` in @davidcarlisle's earlier comment. At that time I did not even check the concrete cases @wilx had to handle,  I just wished to point out that the fact that the test comes out as positive does not mean you can always round to 5 digits after mark and be sure the dimension will come out the same, as my example with ``0.980690003em`` shows. There was not more to it!

As TeX does not consider the unit in its initial parsing of the decimal, and you have only a few use cases, you could also once and for all check which rounding to 5 digits , say here which one of ``0.16666pt`` or ``0.16667pt`` gives the same as ``0.16666666666666666666667pt`` say (either both can give same result, or only one, but it can't be that the two give distinct result from the one obtain from the string with many digits),  It might well be (not tested (*)) that in all your use cases, the naive choice of human decimal rounding to five digits is the correct one, but it requires a check. You can use ``pt`` in this once and for all check as ``em`` plays no rôle yet there. Perhaps in all cases, on will see that naïve rounding is the correct choice...

.... brief testing showed indeed that

```
0.16667 is to be preferred to 0.16666
0.083333 and 0.083334 give the same
0.33333 is to be preferred to 0.33334 (sorry for typo, corrected in edit)
```
 
OK, I launched a systematic search for natural numbers and here are a few examples
```
0.28571pt (from 2/7) gives 18724sp but 0.28571428571428571pt gives 18725sp

0.22222pt (from 2/9) gives 14563sp but 0.22222222222222222pt gives 14564sp

0.15385pt (from 2/13) gives 10083sp but 0.15384615384615385pt gives 10082sp

[...]

0.27273pt (from 3/11) gives 17874sp but 0.27272727272727273pt gives 17873sp

[...]

0.77778pt (from 7/9) gives 50973sp but 0.77777777777777778pt gives 50972sp

[etc]
```

all those demonstrates that rounding something to five decimals may not give exactly same as original.
Each time I tested some decimal obtained from some simple fraction as one may encounter in real life, and the round to 5 digits.

Again this is all a commentary on `0.16667` vs `0.1666666666666666...`

But it is all pretty irrelevant to `uspace` I think !

**Comment by jfbu** [comment]
I corrected a typo, I was hard-pressed by time. Just for fun giving here a few more examples ordered by magnitude:

```
1.27941pt (from 87/68) gives 83847sp but 1.27941176470588235pt gives 83848sp
1.28205pt (from 50/39) gives 84020sp but 1.28205128205128205pt gives 84021sp
1.28333pt (from 77/60) gives 84104sp but 1.28333333333333333pt gives 84105sp
...
1.53333pt (from 23/15) gives 100488sp but 1.53333333333333333pt gives 100489sp
...
7.15385pt (from 93/13) gives 468835sp but 7.15384615384615385pt gives 468834sp
7.22222pt (from 65/9) gives 473315sp but 7.22222222222222222pt gives 473316sp
7.27273pt (from 80/11) gives 476626sp but 7.27272727272727273pt gives 476625sp
7.28571pt (from 51/7) gives 477476sp but 7.28571428571428571pt gives 477477sp
```

each time I started from some simple ratio as one may encounter in real live, and computed if the same result would be obtained by expanding the initial ratio to only five fractional digits or by using the 17 digits which TeX uses. When a mismatch was found the thing was put in log with TeX this time doing the actual computation, for validation.

You can see for example that strings of `3`'s should not always simply truncated, as we might have hoped from the `0.333333333...` case: look at `1.53333.....` case. If we truncate TeX does not compute the same as for the full thing and it is `1.53334` which gives the same.

I am aware this is all about a 1sp difference... and for usual 1em = 10pt, a 10sp difference. It is naturally without relevance for typography as interword spaces will have stretch and shrink on a typical line compensating tiny 10sp. It is all and only to point out that indeed with TeX you don't need more than five digits after decimal mark, but the final digit may not be the one you would guess from a longer decimal expansion.

**Pull request merged**
